[build]
builder = "NIXPACKS"
buildCommand = "cd backend && npm install && npm run build"
watchPatterns = ["backend/**"]

[deploy]
startCommand = "cd backend && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 10

[service]
name = "classical-music-genealogy"